### ISSUE TITLE
netcoreapp3.0 compatibility

### ISSUE THREAD

**Issue by ghost** [paragpkulkarni/SQLiteEncryptionUsingEFCore#3]
Have you tried your example with netcoreapp3.0? 

I have the following settings:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.0.0"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="3.0.0"/>
    <PackageReference Include="SQLitePCLRaw.bundle_sqlcipher" Version="1.1.14" />
    <PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.0.2" ExcludeAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <None Update="blogging.db">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
```

And got the error here:
`
var connection = new SqliteConnection("Data Source=blogging.db");
`

> Exception has occurred: CLR/System.TypeInitializationException
> An unhandled exception of type 'System.TypeInitializationException' occurred in Microsoft.Data.Sqlite.dll: 'The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.'
>  Inner exceptions found, see $exception in variables window for more details.
>  Innermost exception 	 System.MissingMethodException : Method not found: 'Int32 SQLitePCL.ISQLite3Provider.sqlite3_win32_set_directory(Int32, System.String)'.

**Comment by xalix79** [comment]
just found a solution here:
https://stackoverflow.com/questions/57600758/sqlite-method-not-found-intptr-sqlitepcl-sqlite3-get-ptr

**Comment by nd1012** [comment]
I was able to use SQLite with encryption in a .NET Standard 2.1 / .NET Core 3.1 environment using these packages in the .NET Standard library project:

`    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="3.1.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="3.1.6" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" Version="2.0.3" />
`

The trick that made it working for me finally was the `SQLitePCLRaw.bundle_e_sqlcipher` package.

**Comment by paragpkulkarni** [comment]
> I was able to use SQLite with encryption in a .NET Standard 2.1 / .NET Core 3.1 environment using these packages in the .NET Standard library project:
> 
> ` <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.6" /> <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.6"> <PrivateAssets>all</PrivateAssets> <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets> </PackageReference> <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="3.1.6" /> <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="3.1.6" /> <PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" Version="2.0.3" />`
> 
> The trick that made it working for me finally was the `SQLitePCLRaw.bundle_e_sqlcipher` package.

Can you please raise the PR? Thanks.
